# ==============================================================================
#      Universal Production Environment (Conda + Pip) - FINAL & GUARANTEED
# ==============================================================================
# This file defines the exact, fully-pinned software environment, optimized for
# portability, performance, and commercial use. This is the complete and
# verified version.
#
# HOW TO USE:
#   1. conda env remove -n img-simi-prod  (IMPORTANT: Remove failed attempts first!)
#   2. conda env create -f environment.yml --override-channels
#
# PRINCIPLES:
#   - Conda Manages Core Binaries (Python, CUDA, PyTorch, FAISS, NumPy).
#   - Pip Manages Everything Else (as determined by the original environment).

name: image-similarity-env
channels:
  - pytorch
  - nvidia
  - conda-forge
  # - defaults <- This channel has been removed for commercial compliance.
  - nodefaults

dependencies:
  # ----------------------------------------------------------------------------
  # CORE CONDA DEPENDENCIES (Managed by Conda for Stability & Performance)
  # ----------------------------------------------------------------------------
  # These are the absolute essential compiled packages.
  - python=3.10
  - pip
  - ipykernel
  - nbdime=4.0.2     # (added) git diff for notebooks Usage: >> nbdime config-git --enable --global  then =>  nbdiff-web path_to_notebook.ipynb

  # GPU Stack & The Core AI Frameworks
  - cudatoolkit=11.7.1
  - cudnn=8.4.1
  - pytorch=2.0.1
  - pytorch-cuda=11.7
  # --- FIX: Explicitly add torchvision and torchaudio here to install CUDA-enabled versions ---
  - torchvision=0.15.2  
  - torchaudio=2.0.2  
  - faiss-gpu=1.7.4

  # The most critical scientific library, locked to prevent NumPy 2.x issues.
  - numpy=1.26.4

  # ----------------------------------------------------------------------------
  # PIP DEPENDENCIES (All other packages from your environment)
  # ----------------------------------------------------------------------------
  - pip:
    # --- Critical Constraints for Pip Resolver ---
    - numpy==1.26.4      # <-- THE FINAL FIX: Prevents pip from upgrading numpy.
    - websockets==14.0   # FIX: Downgraded for pyautogen
    - timm==0.9.12       # FIX: Downgraded for jk-img-similarity

    # --- Core Scientific Libraries (Sourced from Pip as per solver) ---
    - pandas==2.3.1
    - scipy==1.15.3
    - scikit-learn==1.7.1
    - pillow==10.4.0
    # --- REMOVE torchvision and torchaudio from pip installs to avoid version conflicts ---
    # - torchvision==0.15.2  # REMOVED to force conda CUDA-enabled installs
    # - torchaudio==2.0.2    # REMOVED to force conda CUDA-enabled installs
    - pyarrow==21.0.0

    # --- Frameworks, Servers, & APIs ---
    - Flask==3.1.1
    - Flask-Login==0.6.3
    - Flask-Migrate==4.1.0
    - Flask-SQLAlchemy==3.1.1
    - Flask-WTF==1.2.2
    - WTForms==3.2.1
    - PyJWT==2.10.1  
    - gunicorn==22.0.0
    - fastapi==0.116.1
    - uvicorn==0.35.0
    - waitress==3.0.2
    - shapely==1.8.5.post1
    - streamlit==1.48.0
    - qdrant-client==1.15.1
    - psycopg2-binary==2.9.10
    - openai==1.99.6
    - boto3==1.34.162
    - requests==2.32.4
    - bcrypt==4.3.0 # (added) password hashing algorith designed to securely hash passwords and protect from bruteforce attack
    - pyotp==2.9.0 # (added) for two-factor authentication and token generation

    # --- AI & Computer Vision (Application Level) ---
    - ultralytics==8.3.176
    - transformers==4.53.0
    - tokenizers==0.21.0
    - easyocr==1.7.2
    - opencv-python==4.9.0.80
    - paddleocr==2.10.0
    - paddlepaddle-gpu==2.6.2
    - pytesseract==0.3.13
    - onnxruntime==1.17.3

    # --- Data Plotting & Visualization ---
    - matplotlib==3.10.5
    - seaborn==0.13.2
    - typer==0.16.0
    - openpyxl==3.1.5 # (added) for opening excel file

    # --- Utilities, File Handling, and Other Dependencies ---
    - Faker==37.5.3
    - tiktoken==0.11.0
    - ruamel.yaml==0.18.14
    - PyYAML==6.0.2
    - ipywidgets==8.1.7
    - tqdm==4.67.1
    - pydantic==2.11.7
    - email-validator==2.2.0
    - beautifulsoup4==4.13.4
    - python-dotenv==1.1.1
    - lxml==6.0.0
    - python-docx==1.2.0
    - psutil==7.0.0
    - py-cpuinfo==9.0.0
    - tenacity==8.2.3
    # - pytest==8.4.1  # removed from runtime env to reduce attack surface; use dev/test images only
    - alembic==1.16.4
    - altair==5.5.0
    - annotated-types==0.7.0
    - attrs==25.3.0
    - blinker==1.9.0
    - botocore==1.34.162
    - cachetools==6.1.0
    - click==8.2.1
    - coloredlogs==15.0.1
    - contourpy==1.3.2
    - cycler==0.12.1
    - Cython==3.1.2
    - distro==1.9.0
    - dnspython==2.7.0
    - fonttools==4.59.0
    - fsspec==2025.7.0
    - gitdb==4.0.12
    - GitPython==3.1.45
    - greenlet==3.2.4
    - grpcio==1.74.0
    - huggingface-hub==0.34.4
    - humanfriendly==10.0
    - imageio==2.37.0
    - iniconfig==2.1.0
    - itsdangerous==2.2.0
    - jiter==0.10.0
    - jmespath==1.0.1
    - joblib==1.5.1
    - jsonschema==4.25.0
    - jsonschema-specifications==2025.4.1
    - kiwisolver==1.4.9
    - Mako==1.3.10
    - ninja==1.11.1.4
    - pydantic_core==2.33.2
    - pydeck==0.9.1
    - pyparsing==3.2.3
    - pyreadline3==3.5.4
    - pytz==2025.2
    - rapidfuzz==3.13.0
    - referencing==0.36.2
    - regex==2025.7.34
    - rpds-py==0.27.0
    - ruamel.yaml.clib==0.2.12
    - s3transfer==0.10.4
    - safetensors==0.6.2
    - scikit-image==0.25.2
    - simsimd==6.5.0
    - smmap==5.0.2
    - soupsieve==2.7
    - SQLAlchemy==2.0.42
    - starlette==0.41.2
    - stringzilla==3.12.6
    - termcolor==3.1.0
    - threadpoolctl==3.6.0
    - tifffile==2025.5.10
    - tokenizers==0.21.0
    - toml==0.10.2
    - tomli==2.2.1
    - typing-inspection==0.4.1
    - tzdata==2025.2
    - ultralytics-thop==2.0.15
    - watchdog==6.0.0
    - watchfiles==1.1.0
    - Werkzeug==3.1.3
    - wtforms==3.2.1
    - APScheduler==3.11.0 # (added) for scheduler

  # ------------------------------
  # (added) OPTIONAL: Sphinx Documentation Tools
  # ------------------------------
  # - Sphinx==7.4.7  # removed from runtime image; build docs separately
  # - sphinx-autobuild==2024.10.3
  # - sphinx-rtd-theme==3.0.2
  # - sphinxcontrib-napoleon==0.7
  # - myst-parser==4.0.1
  # - furo==2024.8.6
  # - sphinx-autodoc-typehints==2.3.0
  # - sphinx-copybutton==0.5.2
  # - sphinx-tabs==3.4.7
  # - sphinx-panels==0.4.1
  # - sphinx-intl==2.3.2
  # - sphinxcontrib-serializinghtml==2.0.0
  # Optional system dependencies for PDF generation (not pip):
  # - LaTeX (MiKTeX for Windows, TeX Live for Linux/macOS)